steps:
  - &build
    name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "docker/docker-compose.luigi.yml", "build"]
  - <<: *build
    env: [TAG=$REF_NAME]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/infra/luigi:latest"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/infra/luigi:$REF_NAME"
options:
  logging: CLOUD_LOGGING_ONLY
