---
- name: install dependencies
  apt:
    name:
      - docker-compose
    update_cache: yes

- name: authenticate to artifact repo
  expect:
    command: gcloud auth configure-docker us-central1-docker.pkg.dev
    responses:
      Do you want to continue (Y/n)?: "y"
    creates: /root/.docker/config.json

- name: create directory for config
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - /opt/label-studio
    - /opt/label-studio/data

- name: copy files to remote
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - opt/label-studio/docker-compose.yml

- name: get label-studio oauth2 dotenv from google secrets manager
  command: |
    gcloud secrets versions access latest \
      --secret label_studio_dotenv \
      --out-file /opt/label-studio/.env

- name: get service account from secrets manager
  command: |
    gcloud secrets versions access latest \
      --secret label_studio_key_json \
      --out-file /opt/label-studio/service_account.json

# set the env file to be readable by all users
- name: set permissions on secrets
  file:
    path: /opt/label-studio/{{ item }}
    mode: 0777
  with_items:
    - .env
    - service_account.json

- name: bring up containers
  docker_compose:
    project_src: /opt/label-studio
    pull: true
    state: present
