version: "3.9"
services:
  app:
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - LABEL_STUDIO_PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/label-studio/service_account.json
    volumes:
      - ./data:/label-studio/data:rw
      - ./service_account.json:/label-studio/service_account.json
    command: label-studio
  # https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
  oauth2-proxy:
    restart: always
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    # https://github.com/oauth2-proxy/oauth2-proxy/issues/1669
    command: >
      --email-domain=*
      --upstream=http://app:8080
      --redirect-url=https://${DOMAIN_NAME?domain name not set}/oauth2/callback
      --http-address=0.0.0.0:4181
      --provider=github
      --github-org=dsgt-kaggle-clef
      --scope=user:email
    ports:
      - 4181:4181
    environment:
      - OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET
      - DOMAIN_NAME
    depends_on:
      - app
