version: "3.9"
services:
  luigi:
    build:
      dockerfile: docker/Dockerfile.luigi
      context: ..
      cache_from:
        - us-central1-docker.pkg.dev/dsgt-clef-2024/infra/luigi:latest
    image: us-central1-docker.pkg.dev/dsgt-clef-2024/infra/luigi:${TAG:-latest}
    ports:
      - 8082:8082
    environment:
      - PORT=8082
