---
- name: install apt dependencies
  become: yes
  apt:
    name:
      - python3-pip
      - python3-venv
      - python-is-python3
      - openjdk-11-jdk # for spark
      - libffi-dev # for ansible
      - ffmpeg # for audio processing
      - libsndfile1 # for audio processing
      - aria2
      - nvtop
      - ranger
      - ncdu
    state: present
- name: upgrade pip
  become: yes
  pip:
    name:
      - pip
      - wheel
    state: latest
- name: install pip packages
  become: yes
  pip:
    state: latest
    name:
      - ansible
      - pre-commit
      - pip-tools
      - jupyterlab
      - pyspark
      - matplotlib
      - pandas
      - scikit-learn
      - umap-learn
- name: install torch (GPU)
  become: yes
  pip:
    name:
      - torch
      - torchvision
    state: latest
    extra_args: --index-url https://download.pytorch.org/whl/cu118
- name: install gcs connector for pyspark
  become: yes
  block:
    - name: copy script into usr local bin
      copy:
        src: install_gcs_connector.sh
        dest: /usr/local/bin/install_gcs_connector.sh
        mode: 0755
    - name: run gcs connector script
      shell: /usr/local/bin/install_gcs_connector.sh
