# https://cloud.google.com/compute/docs/disks/add-local-ssd
# configure the filesystem and fstab entry for the local nvme drive
# /dev/disk/by-id/google-local-nvme-ssd-0
- name: add fstab entry
  become: yes
  mount:
    path: /mnt/data
    src: /dev/nvme0n1
    fstype: ext4
    opts: defaults,discard,nofail
    state: present
