plugin: gcp_compute
auth_kind: application
projects:
  - dsgt-clef-2024
regions:
  - us-central1
hostnames:
  - name
filters:
  # either big-disk-dev or regional-gpu-dev
  - labels.disk=raid0
  - labels.version=ubuntu-2204
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
