plugin: gcp_compute
auth_kind: application
projects:
  - dsgt-clef-2024
regions:
  - us-central1
hostnames:
  - name
filters:
  - labels.app=luigi
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
